### ISSUE TITLE
fix docker install to the most recent version

### ISSUE THREAD

**Issue by the-harry** [the-harry/dotfiles#2]
When installing docker it gets an old version, we need to apply this fix:

https://github.com/linkedin/datahub/issues/2020#issuecomment-736850314

**Comment by AKANHO** [comment]
Salut, j'ai un petit soucis avec docker-compose, j'arrive pas à l'utiliser. Besoin d'aide s'il vous plait! Merci
```ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```
J'ai ce texte à chaque fois que je lance la commande "docker-compose up --build"
Merci du retour.

**Comment by the-harry** [comment]
@AKANHO this is a very common error, just run the commands described in 
https://github.com/linkedin/datahub/issues/2020#issuecomment-73685031 and you should be good to go.

**Comment by AKANHO** [comment]
thanks

**Comment by AKANHO** [comment]
HI , j'ai un petit problème lors d'une installation. Comment faire pour corriger ce problème. Merci d'avance.
ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint db (80cdbb51cc41df2054596948210dc8243092772ff131755d9e751ee29f82967c): Error starting userland proxy: listen tcp4 0.0.0.0:3306: bind: address already in use
ERROR: Encountered errors while bringing up the project.

**Comment by the-harry** [comment]
The issue is that you have this port already allocated by some process.
You can find what is the PID of the process by running:

`sudo as -tupln | grep 3306`

After finding the PID you can just kill it by running:

`sudo kill -9 PID`

But since this is the default mysql port you can also just stop the service by running:

`sudo systemctl stop mysql.service`
